// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Box: typeof import('./src/components/Library/Box.vue')['default']
    Home: typeof import('./src/components/Home/Home.vue')['default']
    Library: typeof import('./src/components/Library/Library.vue')['default']
    MenuSlider: typeof import('./src/components/MenuSlider/MenuSlider.vue')['default']
    NavBarMenu: typeof import('./src/components/NavBarMenu/NavBarMenu.vue')['default']
    Payment: typeof import('./src/components/Payment/Payment.vue')['default']
    PaymentItem: typeof import('./src/components/Payment/PaymentItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThumbnailItem: typeof import('./src/components/Library/ThumbnailItem.vue')['default']
  }
}
